name: Build Images
on:
  workflow_dispatch:
  push:
    branches:
    - main
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Build Images {0}', github.ref_name) || '' }}
jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Install buildah
      if: false
      run: sudo apt update && sudo apt install buildah
    - name: Checkout runner-images
      uses: actions/checkout@v3
      with:
        repository: actions/runner-images
        ref: main
    - name: Build Image
      run: |
        function exec() {
          $path, $myargs = $args
          $proc=Start-Process -Wait -PassThru -FilePath $path -Args $myargs
          if($proc.ExitCode -ne 0) {
            throw "$args failed with exit code $proc.ExitCode"
          }
        }
        function exec_out() {
          $path, $myargs = $args
          $stdout = "$(& "$path" $myargs)"
          if($LASTEXITCODE -ne 0) {
            throw "$args failed with exit code $LASTEXITCODE"
          }
          return "$stdout"
        }
        exec buildah login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io
        exec buildah from --format=docker --name onbuild-container ubuntu:latest
        $containerpath = "$(exec_out buildah mount onbuild-container)"
        Get-Content "$containerpath/etc/environment"
        exec buildah config --env onbuild-container
        exec buildah unmount onbuild-container
        exec buildah commit --format=docker onbuild-container onbuild-image
        exec buildah push onbuild-image "docker://ghcr.io/${{ github.repository_owner }}/buildah-images:latest".ToLower()
      shell: buildah unshare pwsh "{0}"
